### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/csaf-validator-service#26]
Update the `package-lock.json` to fix vulnerabilities in the backend
- `got`
- `minimist`
- `undici`

**Comment by cloeser** [comment]
Only dev dependencies. Will be addressed before release 1.0.0.

**Comment by tschmidtb51** [comment]
Done in https://github.com/secvisogram/csaf-validator-service/commit/5d9d524abe308c2f848002e75c7d0a7b84f9c866
