### ISSUE TITLE
Issue with building docker image

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/csaf-validator-service#51]
If you try to build the docker image with a reference to the git repository (`docker build https://github.com/secvisogram/csaf-validator-service.git#main`), there is a problem with the git submodules. The following error is thrown:
```
unable to prepare context: unable to 'git clone' to temporary context directory: error initializing submodules: fatal: Keine URL für Submodul-Pfad 'csaf-validator-lib/csaf' in .gitmodules gefunden
: exit status 128
```

Is it possible to add a `.gitmodules` in the base folder?
```
[submodule "csaf-validator-lib/csaf"]
	path = csaf-validator-lib/csaf
	url = https://github.com/oasis-tcs/csaf.git
```

I tested it on a fork and have not recognized any problems.

**Comment by tschmidtb51** [comment]
> Is it possible to add a `.gitmodules` in the base folder?

Theoretically, yes. However, we shouldn't need that as there is already a [`.gitmodules` in the `csaf-validator-lib` directory](https://github.com/secvisogram/csaf-validator-service/blob/main/csaf-validator-lib/.gitmodules). So, I think the problem is deeper within...

**Comment by tschmidtb51** [comment]
I figured out that `csaf-validator-lib` is currently not recognized as a `subtree`. We need to check whether that is correct...
